# Lazygit configuration file
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

promptToReturnFromSubprocess: false

gui:
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
  # Show icons in file tree (requires nerd font)
  showIcons: true
  # Show file tree icons even in terminals that don't support unicode
  nerdFontsVersion: "3"
git:
  # Use delta for better diffs (if installed)
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  # Fetch branches when refreshing
  autoFetch: true
  # Show whole commit graph by default
  log:
    showWholeGraph: true
keybinding:
  universal:
    quit: 'q'
    quit-alt1: '<c-c>'
    return: '<esc>'
    quitWithoutChangingDirectory: 'Q'
    togglePanel: '<tab>'
    prevItem: '<up>'
    nextItem: '<down>'
    prevItem-alt: 'k'
    nextItem-alt: 'j'
    prevPage: ','
    nextPage: '.'
    scrollLeft: 'H'
    scrollRight: 'L'
    gotoTop: '<'
    gotoBottom: '>'
    toggleRangeSelect: 'v'
    rangeSelectDown: '<s-down>'
    rangeSelectUp: '<s-up>'
    prevBlock: '<left>'
    nextBlock: '<right>'
    prevBlock-alt: 'h'
    nextBlock-alt: 'l'
    nextBlock-alt2: '<tab>'
    prevBlock-alt2: '<backtab>'
    jumpToBlock: ['1', '2', '3', '4', '5']
    nextMatch: 'n'
    prevMatch: 'N'
    startSearch: '/'
    optionMenu: <disabled>
    optionMenu-alt1: '?'
    select: '<space>'
    goInto: '<enter>'
    confirm: '<enter>'
    confirmInEditor: '<a-enter>'
    remove: 'd'
    new: 'n'
    edit: 'e'
    openFile: 'o'
    scrollUpMain: '<pgup>'
    scrollDownMain: '<pgdown>'
    scrollUpMain-alt1: 'K'
    scrollDownMain-alt1: 'J'
    scrollUpMain-alt2: '<c-u>'
    scrollDownMain-alt2: '<c-d>'
    executeShellCommand: ':'
    createRebaseOptionsMenu: 'm'
    # Push/pull/fetch
    pushFiles: 'P'
    pullFiles: 'p'
    # Undo/redo
    undo: '<c-z>'
    redo: '<c-y>'
    # Copy
    copyToClipboard: '<c-o>'
    # Help
    openMergeTool: 'M'
  status:
    checkForUpdate: 'u'
    recentRepos: '<enter>'
    allBranchesLogGraph: 'a'
  files:
    commitChanges: 'c'
    commitChangesWithoutHook: 'w'
    amendLastCommit: 'A'
    commitChangesWithEditor: 'C'
    findBaseCommitForFixup: '<c-f>'
    confirmDiscard: 'x'
    ignoreFile: 'i'
    refreshFiles: 'r'
    stashAllChanges: 's'
    viewStashOptions: 'S'
    toggleStagedAll: 'a'
    viewResetOptions: 'D'
    fetch: 'f'
    toggleTreeView: '`'
    openMergeTool: 'M'
    openStatusFilter: '<c-b>'
    quit: 'q'
  branches:
    createPullRequest: 'o'
    viewPullRequestOptions: 'O'
    copyPullRequestURL: '<c-y>'
    checkoutBranchByName: 'c'
    forceCheckoutBranch: 'F'
    rebaseBranch: 'r'
    renameBranch: 'R'
    mergeIntoCurrentBranch: 'M'
    viewGitFlowOptions: 'i'
    fastForward: 'f'
    createTag: 'T'
    pushTag: 'P'
    setUpstream: 'u'
    fetchRemote: 'f'
    sortOrder: 's'
  worktrees:
    viewWorktreeOptions: 'w'
  commits:
    squashDown: 's'
    renameCommit: 'r'
    renameCommitWithEditor: 'R'
    viewResetOptions: 'g'
    markCommitAsFixup: 'f'
    createFixupCommit: 'F'
    squashAboveCommits: 'S'
    moveDownCommit: '<c-j>'
    moveUpCommit: '<c-k>'
    amendToCommit: 'A'
    resetCommitAuthor: 'a'
    pickCommit: 'p'
    revertCommit: 't'
    cherryPickCopy: 'C'
    pasteCommits: 'V'
    markCommitAsBaseForRebase: 'B'
    tagCommit: 'T'
    checkoutCommit: '<space>'
    resetCherryPick: '<c-R>'
    copyCommitAttributeToClipboard: 'y'
    openLogMenu: '<c-l>'
    openInBrowser: 'o'
    viewBisectOptions: 'b'
    startInteractiveRebase: 'i'
  amendAttribute:
    resetAuthor: 'a'
    setAuthor: 'A'
    addCoAuthor: 'c'
  stash:
    popStash: 'g'
    renameStash: 'r'
  commitFiles:
    checkoutCommitFile: 'c'
  main:
    toggleSelectHunk: 'a'
    pickBothHunks: 'b'
    editSelectHunk: 'E'
  submodules:
    init: 'i'
    update: 'u'
    bulkMenu: 'b'
# OS-specific overrides
os:
  edit: 'NVIM_APPNAME=bavim nvim --server $NVIM --remote-tab {{filename}}'
  editAtLine: 'NVIM_APPNAME=bavim nvim --server $NVIM --remote-tab {{filename}} +{{line}}'
# Custom commands
customCommands:
  - key: '<c-v>'
    context: 'global'
    description: 'Open lazygit config in editor'
    command: 'nvim ~/.config/lazygit/config.yml'
  - key: 'D'
    context: 'files'
    description: 'Open file in diffview'
    command: 'NVIM_APPNAME=bavim nvim -c "DiffviewOpen -- {{.SelectedFile.Name}}" {{.SelectedFile.Name}}'
